repository: KilfaneDM/KilfaneDM.github.io
theme: minimal-mistakes-jekyll

author:
  name: "Daren Murray"
  bio: "IT Software Developer student at NBCC"
  email: "bleckolshnork64@gmail.com"

include:
  - _pages
  - _assets

gallery:
  dir: assets/images
  symlink: false
  galleries:
    - dir: drone
      name: "Drone Photography"
    - dir: ground
      name: "Photography"

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
