repository: KilfaneDM/KilfaneDM.github.io
theme: minimal-mistakes-jekyll

author:
  name: "Daren Murray"
  bio: "IT Software Developer student at NBCC"
  email: "bleckolshnork64@gmail.com"
  
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
